### ISSUE TITLE
java.lang.Exception: Unknown field clock_time_get

### ISSUE THREAD

**Issue by orestisfl** [satabin/swam#83]
## What I did

Extract this [randombytes.zip](https://github.com/satabin/swam/files/4902188/randombytes.zip) in the cwd and run:

```shell
./millw cli.run run -d --wasi --dir=. randombytes
java.lang.Exception: Unknown field clock_time_get
	at swam.runtime.wasi.Wasi$$anon$1.find(Wasi.scala:33)
	at swam.runtime.wasi.Wasi$$anon$1.find(Wasi.scala:33)
	at swam.runtime.imports.TCImports.find(Imports.scala:50)
	at swam.runtime.internals.instance.Instantiator.$anonfun$check$1(Instantiator.scala:56)
	at cats.StackSafeMonad.tailRecM(StackSafeMonad.scala:15)
	at cats.StackSafeMonad.tailRecM$(StackSafeMonad.scala:15)
	at cats.effect.IOLowPriorityInstances$IOEffect.tailRecM(IO.scala:792)
	at cats.StackSafeMonad.$anonfun$tailRecM$1(StackSafeMonad.scala:16)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:142)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:88)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:89)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:89)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:89)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:69)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:49)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:359)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:380)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:323)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:359)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:380)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:323)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:35)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
1 targets failed
cli.run subprocess failed
```

Like in #80, this is from the libsodium test suite and it works with wasmer (I promise this is the last problem I found :))

**Comment by satabin** [comment]
I forgot to export the clocks in the WASI module, I will fix it.
