### ISSUE TITLE
scodec.stream.CodecError: unexpected end of input

### ISSUE THREAD

**Issue by orestisfl** [satabin/swam#91]
## What I did

Extract [scalarmult8.zip](https://github.com/satabin/swam/files/4911244/scalarmult8.zip) to the cwd and execute `./millw cli.run run --wasi --dir=. scalarmult8`

Also, I verified that wasmer can execute the file

## What I get

```
swam.runtime.CompileException: An error occurred during compilation
	at swam.runtime.internals.compiler.Compiler.$anonfun$compile$15(Compiler.scala:236)
	at swam.runtime.internals.compiler.Compiler.$anonfun$compile$15$adapted(Compiler.scala:236)
	at fs2.Stream$.$anonfun$handleErrorWith$1(Stream.scala:1551)
	at fs2.internal.FreeC$$anon$5.cont(FreeC.scala:68)
	at fs2.internal.FreeC$ViewL$$anon$9$$anon$10.cont(FreeC.scala:203)
	at fs2.internal.FreeC$ViewL$.mk(FreeC.scala:192)
	at fs2.internal.FreeC$ViewL$.apply(FreeC.scala:183)
	at fs2.internal.FreeC.viewL(FreeC.scala:83)
	at fs2.internal.Algebra$.go$1(Algebra.scala:178)
	at fs2.internal.Algebra$.$anonfun$compileLoop$16(Algebra.scala:310)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:145)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: scodec.stream.CodecError: unexpected end of input
```

PS:
- Once again from the [libsodium testsuite](https://github.com/jedisct1/libsodium/)
- Binaries not stripped this time
- All other tests pass :100:

**Comment by satabin** [comment]
Wow, a codec bug, it's been a while. I'll have a look.

**Comment by satabin** [comment]
I tested locally, this one is interesting. The wasm file has 2 extra bytes after the last section. Same problem occurs here: https://wwwg.github.io/web-wasmdec/ when trying to decompile the wasm file. I can run the included `--wat` file with success:

```shell
❯ mill cli.run run --wasi --wat --dir . scalarmult8.wat
[128/128] cli.run
❯ echo $?
0
```
But there seems to be some overflow reached in the codec (fails when I try to compile the wat to wasm with swam)

**Comment by satabin** [comment]
@orestisfl as a test, could you compile the files without debug symbols?
